
COMPILER = javac

JVM = java

SRC = *.java

TRASH = *.class

TARGET = # This is the name of the file that contains your main function

all:
	$(COMPILER) $(SRC)

clean:
	rm -f $(TRASH)
	rm $(TARGET)

run:
	$(JVM) $(TARGET)
